### ISSUE TITLE
Support S3 compatible as cache backend

### ISSUE THREAD

**Issue by mekza** [paylogic/pip-accel#44]
Riak CS and Swift are widely used, it will be great to be able to store binary cache in Riak CS or Swift.

**Comment by xolox** [comment]
I'm going to go ahead and close this issue now, because the test suite has been running based on the code added in this feature request and it has been working fine for quite a while - people are using it. The code was even extended further in #45.

@mekza: If you believe your feature request wasn't implemented correctly then please feel free to reopen this issue. Thanks for suggesting the feature!
